services:
  api-gateway:
    build:
      context: ../services/api-gateway
    container_name: api-gateway
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      NODE_ENV: development
      AUTH_SERVICE_URL: http://auth-service:3001
    depends_on:
      - auth-service

  auth-service:
    build:
      context: ../services/auth-service
    container_name: auth-service
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      NODE_ENV: development
      POSTGRES_URL: postgresql://postgres:postgres@postgres:5432/auth_service
      JWT_SECRET: change_me_in_dev
      JWT_EXPIRES_IN: 15m
      REFRESH_TOKEN_EXPIRES_IN: 7d
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  redis_data: